Add functionality to rebuild only one initramfs

diff --git a/rebuild-initramfs b/rebuild-initramfs
--- a/rebuild-initramfs
+++ b/rebuild-initramfs
@@ -4,6 +4,8 @@ do_build=
 verbose=
 default_yes=
 quiet=
+hook=
+rebuild_for=
 
 prompt() {
     while true; do
@@ -25,64 +27,7 @@ sudo_if_required() {
     fi
 }
 
-print_help() {
-    cat <<EOF
-rebuild-initramfs: rebuild some (or all) initramfs images using dracut.
-
-Usage: rebuild-initramfs [-h | --help] [-v | --verbose]
-Command line options:
-    -h, --help: prints this help message
-    -y, --yes: say "yes" to all questions
-    -v, --verbose: be more verbose
-    -q, --quiet: be quiet
-EOF
-}
-
-if [[ -t 1 ]]; then
-    YELLOW="\e[33m"
-    COLOROFF="\e[39m"
-fi
-
-# shellcheck disable=SC2059
-[[ $(id -u) == 0 ]] && ([[ -z "$SUDO_UID" ]] ||
-    printf "${YELLOW}WARNING:${COLOROFF} Don't run this script with sudo. This script will call out to sudo if required.\n" >&2)
-
-for arg in "$@"
-do
-    case $arg in
-        -v|--verbose)
-            verbose=1
-            echo "Running in verbose mode."
-            shift;;
-        -y|--yes)
-            default_yes=1
-            shift;;
-        -q|--quiet)
-            quiet=1
-            shift;;
-        -h|--help)
-            print_help
-            exit;;
-    esac
-done
-
-if [[ "$verbose" == "1" ]] && [[ "$quiet" == "1" ]]; then
-    >&2 echo "Cannot be verbose and quiet simultaneously!"
-    exit 1
-fi
-
-# Generate a list of kernels to work on
-mapfile -t kernels < <(ls -d /usr/lib/modules/*/)
-
-for k in "${kernels[@]}"; do
-    version=$(basename "$k")
-    base=$(pacman -Qoq "$k" 2>/dev/null | head -n 1)
-
-    if [[ "$base" == "" ]]; then
-        [[ -z $verbose ]] || >&2 echo "${version} is detected, but it is not an installed kernel!"
-        break
-    fi
-    
+rebuild_for_base() {
     [[ -n $default_yes ]] && [[ -n $quiet ]] || printf 'Rebuild initramfs for: %s...\n' "$base"
 
     if [[ -z $default_yes ]]; then
@@ -110,6 +55,92 @@ for k in "${kernels[@]}"; do
         fi
     else
         [[ -z $verbose ]] || echo "Not rebuilding initramfs image for ${version}."
-    fi 
+    fi
+}
+
+print_help() {
+    cat <<EOF
+rebuild-initramfs: rebuild some (or all) initramfs images using dracut.
+
+Usage: rebuild-initramfs [-h | --help] [-v | --verbose]
+Command line options:
+    -h, --help: prints this help message
+    -y, --yes: say "yes" to all questions
+    -v, --verbose: be more verbose
+    -k, --hook: running inside a pacman/ALPM hook
+    -q, --quiet: be quiet
+EOF
+}
+
+if [[ -t 1 ]]; then
+    YELLOW="\e[33m"
+    COLOROFF="\e[39m"
+fi
+
+for arg in "$@"
+do
+    case $arg in
+        -v|--verbose)
+            verbose=1
+            echo "Running in verbose mode."
+            shift;;
+        -y|--yes)
+            default_yes=1
+            shift;;
+        -q|--quiet)
+            quiet=1
+            shift;;
+        -h|--help)
+            print_help
+            exit 1;;
+        -k|--hook)
+            hook=1
+            shift;;
+        *)
+            rebuild_for=$arg
+            shift;;
+    esac
+done
+
+# shellcheck disable=SC2059
+[[ $(id -u) == 0 ]] && ([[ -z "$SUDO_UID" ]] || ([[ -n "$hook" ]] ||
+    printf "${YELLOW}WARNING:${COLOROFF} Don't run this script with sudo. This script will call out to sudo if required.\n" >&2))
+
+if [[ "$verbose" == "1" ]] && [[ "$quiet" == "1" ]]; then
+    >&2 echo "Cannot be verbose and quiet simultaneously!"
+    exit 1
+fi
+
+if [ -n "$rebuild_for" ]; then
+    pacman -Q "$rebuild_for" > /dev/null 2>&1
+    if [[ $? -ne 0 ]]; then
+        >&2 echo "ERROR: $rebuild_for is not an installed kernel!"
+        exit 1
+    fi
+
+    printf 'Rebuidling for %s...\n' "$rebuild_for"
+
+    base="$rebuild_for"
+    _path=$(pacman -Ql "$rebuild_for" | grep "/usr/lib/modules/.\+" | head -n 1 | sed 's/^[^[:space:]]*[[:space:]]\{1,\}//')
+    version=$(basename "$_path")
+
+    rebuild_for_base
+
+    exit
+fi
+
+# Generate a list of kernels to work on
+mapfile -t kernels < <(ls -d /usr/lib/modules/*/)
+
+for k in "${kernels[@]}"; do
+    version=$(basename "$k")
+    base=$(pacman -Qoq "$k" 2>/dev/null | head -n 1)
+
+    if [[ "$base" == "" ]]; then
+        [[ -z $verbose ]] || >&2 echo "${version} is detected, but it is not an installed kernel!"
+        break
+    fi
+    
+    rebuild_for_base
 done
 
